# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/custom-functions-metadata"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/custom-functions-metadata-plugin"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-office-addins"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/eslint-plugin-excel-custom-functions"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/eslint-plugin-office-addins"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-debugging"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-dev-certs"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-dev-settings"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-lint"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-manifest"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-node-debugger"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-sso"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-test-helpers"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-test-server"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/office-addin-usage-data"
    schedule:
      interval: "daily"
